apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: workercontagem-scaledobject
spec:
  scaleTargetRef:
    name: workercontagem
  pollingInterval: 15
  cooldownPeriod:  30
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: rabbitmq
    metadata:
      host: <STRING DE CONEXÃO RABBITMQ>
      protocol: amqp
      mode: QueueLength
      value: "2"
      queueName: queue-testes
      vhostName: /